/* The following code was generated by JFlex 1.7.0 */

package Analizadores;
import java_cup.runtime.Symbol; 
import java.util.ArrayList;

import Clases.Errores;
import Clases.Tokens;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Lexico</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\10\1\12\1\12\1\11\22\0\1\1\1\0\1\6"+
    "\4\0\1\13\1\46\1\47\1\15\1\0\1\61\1\0\1\3\1\14"+
    "\12\2\1\62\1\60\1\57\1\55\1\56\1\0\1\54\1\22\1\31"+
    "\1\33\1\26\1\24\1\4\1\21\1\34\1\40\1\44\1\4\1\32"+
    "\1\23\1\25\1\20\1\16\1\4\1\17\1\36\1\43\1\30\1\27"+
    "\1\4\1\42\1\45\1\41\1\52\1\7\1\53\1\0\1\5\1\0"+
    "\1\22\1\31\1\33\1\26\1\24\1\4\1\21\1\34\1\40\1\44"+
    "\1\4\1\32\1\23\1\25\1\20\1\16\1\4\1\17\1\36\1\43"+
    "\1\30\1\27\1\4\1\42\1\45\1\41\1\50\1\0\1\51\7\0"+
    "\1\12\113\0\1\4\37\0\1\4\76\0\2\37\115\0\1\35\u1ea8\0"+
    "\1\12\1\12\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\2\1\13\5\1\1\2\5\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\2\0\1\24\3\0\1\25\1\0\10\5\1\0"+
    "\5\5\1\0\5\5\1\0\1\5\1\0\1\5\1\0"+
    "\1\5\1\26\1\25\1\0\1\5\1\0\1\5\2\27"+
    "\1\5\1\30\1\31\1\32\1\5\1\33\2\34\1\35"+
    "\3\5\2\36\1\37\5\5\1\0\1\5\2\40\1\0"+
    "\1\5\1\2\1\5\1\0\2\5\1\41\1\0\1\5"+
    "\1\42\1\43\1\44\1\5\1\0\3\5\1\0\2\5"+
    "\1\45\1\0\1\5\1\0\2\5\2\46\1\5\2\47"+
    "\1\5\1\0\2\5\1\50\1\0\2\5\1\0\1\5"+
    "\1\0\5\5\1\0\1\5\1\51\1\0\1\5\2\52"+
    "\1\0\1\5\1\53\1\0\1\5\2\54\1\55\1\0"+
    "\2\5\1\0\1\5\2\56\1\0\1\5\2\57\1\0"+
    "\1\5\1\60\1\61\1\60\1\61\2\62\1\63\1\0"+
    "\1\5\2\64\1\0\1\5\2\65\2\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[196];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\63\0\314\0\377\0\63"+
    "\0\u0132\0\u0165\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297"+
    "\0\u02ca\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc\0\u042f"+
    "\0\63\0\63\0\63\0\63\0\63\0\63\0\63\0\63"+
    "\0\63\0\63\0\63\0\63\0\63\0\u0462\0\377\0\63"+
    "\0\u0495\0\u04c8\0\u04fb\0\u04c8\0\u052e\0\u0561\0\u0594\0\u05c7"+
    "\0\u05fa\0\u062d\0\u0660\0\u0693\0\u06c6\0\u06f9\0\u072c\0\u075f"+
    "\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u085e\0\u0891\0\u08c4\0\u08f7"+
    "\0\u092a\0\u095d\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\u0a5c\0\u0462"+
    "\0\63\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28\0\63\0\314\0\u0b5b"+
    "\0\314\0\u0b8e\0\314\0\u0bc1\0\314\0\63\0\314\0\314"+
    "\0\u0bf4\0\u0c27\0\u0c5a\0\63\0\314\0\u0c8d\0\u0cc0\0\u0cf3"+
    "\0\u0d26\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2\0\63\0\314\0\u0e25"+
    "\0\u0e58\0\63\0\u0e8b\0\u0ebe\0\u0ef1\0\u0f24\0\314\0\u0f57"+
    "\0\u0f8a\0\314\0\314\0\314\0\u0fbd\0\u0ff0\0\u1023\0\u1056"+
    "\0\u1089\0\u10bc\0\u10ef\0\u1122\0\314\0\u1155\0\u1188\0\u11bb"+
    "\0\u11ee\0\u1221\0\63\0\314\0\u1254\0\u1287\0\u12ba\0\u12ed"+
    "\0\u1320\0\u1353\0\u1386\0\314\0\u13b9\0\u13ec\0\u141f\0\u1452"+
    "\0\u1485\0\u14b8\0\u14eb\0\u151e\0\u1551\0\u1584\0\u15b7\0\u15ea"+
    "\0\u161d\0\314\0\u1650\0\u1683\0\63\0\314\0\u16b6\0\u16e9"+
    "\0\314\0\u171c\0\u174f\0\u1782\0\u17b5\0\314\0\u17e8\0\u181b"+
    "\0\u184e\0\u1881\0\u18b4\0\63\0\314\0\u18e7\0\u191a\0\63"+
    "\0\314\0\u194d\0\u1980\0\63\0\63\0\314\0\314\0\63"+
    "\0\314\0\314\0\u19b3\0\u19e6\0\63\0\314\0\u1a19\0\u1a4c"+
    "\0\63\0\314\0\63\0\314";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[196];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\2\1\7\1\2"+
    "\1\10\1\3\1\0\1\11\1\12\1\2\1\13\1\14"+
    "\1\6\1\15\1\16\1\17\1\20\1\6\1\21\1\22"+
    "\2\6\1\23\1\24\1\25\1\26\1\27\1\2\3\6"+
    "\1\30\2\6\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\64\0"+
    "\1\3\7\0\1\3\53\0\1\4\1\46\61\0\1\6"+
    "\1\0\2\6\10\0\17\6\1\0\1\6\1\0\6\6"+
    "\15\0\6\47\1\50\1\51\53\47\6\52\1\0\1\53"+
    "\3\52\1\54\47\52\15\0\1\55\47\0\1\6\1\0"+
    "\2\6\10\0\1\6\1\56\15\6\1\0\1\6\1\0"+
    "\6\6\17\0\1\6\1\0\2\6\10\0\6\6\1\57"+
    "\10\6\1\0\1\6\1\0\6\6\17\0\1\6\1\0"+
    "\2\6\10\0\1\6\1\60\15\6\1\0\1\6\1\0"+
    "\6\6\17\0\1\6\1\0\2\6\10\0\1\6\1\61"+
    "\15\6\1\0\1\6\1\0\6\6\17\0\1\6\1\0"+
    "\2\6\10\0\2\6\1\62\1\6\1\63\1\6\1\64"+
    "\3\6\1\65\4\6\1\0\1\6\1\66\1\67\5\6"+
    "\17\0\1\6\1\0\2\6\10\0\7\6\1\70\7\6"+
    "\1\0\1\6\1\0\2\6\1\71\1\6\1\72\1\6"+
    "\17\0\1\6\1\0\2\6\10\0\2\6\1\73\14\6"+
    "\1\0\1\6\1\74\1\75\5\6\17\0\1\6\1\0"+
    "\2\6\10\0\4\6\1\76\12\6\1\0\1\6\1\0"+
    "\6\6\17\0\1\6\1\0\2\6\10\0\4\6\1\77"+
    "\12\6\1\0\1\6\1\0\6\6\17\0\1\6\1\0"+
    "\2\6\10\0\2\6\1\100\13\6\1\101\1\0\1\6"+
    "\1\0\6\6\17\0\1\6\1\0\2\6\10\0\17\6"+
    "\1\0\1\6\1\102\1\103\5\6\45\0\1\104\34\0"+
    "\1\6\1\0\2\6\10\0\12\6\1\105\4\6\1\0"+
    "\1\6\1\0\6\6\17\0\1\6\1\0\2\6\10\0"+
    "\17\6\1\0\1\6\1\106\1\107\5\6\17\0\1\110"+
    "\60\0\10\47\3\0\50\47\13\0\1\111\47\0\10\52"+
    "\3\0\50\52\15\55\1\112\45\55\2\0\1\6\1\0"+
    "\2\6\10\0\2\6\1\113\14\6\1\0\1\6\1\114"+
    "\1\115\5\6\17\0\1\6\1\0\2\6\10\0\17\6"+
    "\1\116\1\117\1\0\6\6\17\0\1\6\1\0\2\6"+
    "\10\0\4\6\1\120\12\6\1\0\1\6\1\0\6\6"+
    "\17\0\1\6\1\0\2\6\10\0\1\6\1\121\15\6"+
    "\1\0\1\6\1\0\6\6\17\0\1\6\1\0\2\6"+
    "\10\0\10\6\1\122\6\6\1\0\1\6\1\0\6\6"+
    "\17\0\1\6\1\0\2\6\10\0\17\6\1\0\1\6"+
    "\1\0\2\6\1\123\3\6\17\0\1\6\1\0\2\6"+
    "\10\0\10\6\1\124\6\6\1\0\1\6\1\0\6\6"+
    "\17\0\1\6\1\0\2\6\10\0\14\6\1\125\2\6"+
    "\1\0\1\6\1\0\6\6\42\0\1\126\37\0\1\6"+
    "\1\0\2\6\10\0\7\6\1\127\7\6\1\0\1\6"+
    "\1\0\6\6\17\0\1\6\1\0\2\6\10\0\10\6"+
    "\1\130\6\6\1\0\1\6\1\0\6\6\17\0\1\6"+
    "\1\0\2\6\10\0\6\6\1\131\10\6\1\0\1\6"+
    "\1\0\6\6\17\0\1\6\1\0\2\6\10\0\6\6"+
    "\1\132\10\6\1\0\1\6\1\0\6\6\17\0\1\6"+
    "\1\0\2\6\10\0\12\6\1\133\4\6\1\0\1\6"+
    "\1\0\6\6\44\0\1\134\35\0\1\6\1\0\2\6"+
    "\10\0\11\6\1\135\5\6\1\0\1\6\1\0\6\6"+
    "\17\0\1\6\1\0\2\6\10\0\1\6\1\136\12\6"+
    "\1\137\2\6\1\0\1\6\1\0\6\6\17\0\1\6"+
    "\1\0\2\6\10\0\13\6\1\140\3\6\1\0\1\6"+
    "\1\0\6\6\17\0\1\6\1\0\2\6\10\0\7\6"+
    "\1\141\4\6\1\142\2\6\1\0\1\6\1\0\6\6"+
    "\17\0\1\6\1\0\2\6\10\0\4\6\1\143\12\6"+
    "\1\0\1\6\1\0\6\6\52\0\2\144\26\0\1\6"+
    "\1\0\2\6\10\0\17\6\1\144\1\145\1\0\6\6"+
    "\40\0\1\146\41\0\1\6\1\0\2\6\10\0\5\6"+
    "\1\147\11\6\1\0\1\6\1\0\6\6\60\0\1\150"+
    "\21\0\1\6\1\0\2\6\10\0\17\6\1\0\1\6"+
    "\1\0\3\6\1\151\2\6\15\0\14\55\1\152\1\112"+
    "\45\55\2\0\1\6\1\0\2\6\10\0\3\6\1\153"+
    "\13\6\1\0\1\6\1\0\6\6\42\0\1\154\37\0"+
    "\1\6\1\0\2\6\10\0\7\6\1\155\7\6\1\0"+
    "\1\6\1\0\6\6\17\0\1\6\1\0\2\6\10\0"+
    "\1\156\16\6\1\0\1\6\1\0\6\6\17\0\1\6"+
    "\1\0\2\6\10\0\4\6\1\157\12\6\1\0\1\6"+
    "\1\0\6\6\17\0\1\6\1\0\2\6\10\0\17\6"+
    "\1\0\1\6\1\160\1\161\5\6\17\0\1\6\1\0"+
    "\2\6\10\0\15\6\1\162\1\6\1\0\1\6\1\0"+
    "\6\6\17\0\1\6\1\0\2\6\10\0\17\6\1\0"+
    "\1\6\1\0\2\6\1\163\2\6\1\164\17\0\1\6"+
    "\1\0\2\6\10\0\13\6\1\165\3\6\1\0\1\6"+
    "\1\0\6\6\17\0\1\6\1\0\2\6\10\0\17\6"+
    "\1\0\1\6\1\166\1\167\5\6\17\0\1\6\1\0"+
    "\2\6\10\0\12\6\1\170\4\6\1\0\1\6\1\0"+
    "\6\6\17\0\1\6\1\0\2\6\10\0\6\6\1\171"+
    "\10\6\1\0\1\6\1\0\6\6\17\0\1\6\1\0"+
    "\2\6\10\0\17\6\1\172\1\173\1\0\6\6\17\0"+
    "\1\6\1\0\2\6\10\0\12\6\1\174\4\6\1\0"+
    "\1\6\1\0\6\6\17\0\1\6\1\0\2\6\10\0"+
    "\1\6\1\175\15\6\1\0\1\6\1\0\6\6\60\0"+
    "\1\176\21\0\1\6\1\0\2\6\10\0\17\6\1\0"+
    "\1\6\1\0\3\6\1\177\2\6\45\0\1\200\34\0"+
    "\1\6\1\0\2\6\10\0\12\6\1\201\4\6\1\0"+
    "\1\6\1\0\6\6\17\0\1\6\1\0\2\6\10\0"+
    "\1\6\1\202\15\6\1\0\1\6\1\0\6\6\60\0"+
    "\1\203\21\0\1\6\1\0\2\6\10\0\17\6\1\0"+
    "\1\6\1\0\3\6\1\204\2\6\17\0\1\6\1\0"+
    "\2\6\10\0\16\6\1\205\1\0\1\6\1\0\6\6"+
    "\37\0\1\206\42\0\1\6\1\0\2\6\10\0\4\6"+
    "\1\207\12\6\1\0\1\6\1\0\6\6\17\0\1\6"+
    "\1\0\2\6\10\0\14\6\1\210\2\6\1\0\1\6"+
    "\1\0\6\6\37\0\1\211\42\0\1\6\1\0\2\6"+
    "\10\0\4\6\1\212\12\6\1\0\1\6\1\0\6\6"+
    "\17\0\1\6\1\0\2\6\10\0\6\6\1\213\10\6"+
    "\1\0\1\6\1\0\6\6\17\0\1\6\1\0\2\6"+
    "\10\0\14\6\1\214\2\6\1\0\1\6\1\0\6\6"+
    "\35\0\1\215\44\0\1\6\1\0\2\6\10\0\2\6"+
    "\1\216\14\6\1\0\1\6\1\0\6\6\17\0\1\6"+
    "\1\0\2\6\10\0\5\6\1\217\11\6\1\0\1\6"+
    "\1\0\6\6\35\0\1\220\44\0\1\6\1\0\2\6"+
    "\10\0\2\6\1\221\14\6\1\0\1\6\1\0\6\6"+
    "\47\0\1\222\32\0\1\6\1\0\2\6\10\0\14\6"+
    "\1\223\2\6\1\0\1\6\1\0\6\6\17\0\1\6"+
    "\1\0\2\6\10\0\4\6\1\224\12\6\1\0\1\6"+
    "\1\0\6\6\17\0\1\6\1\0\2\6\10\0\1\225"+
    "\12\6\1\226\1\227\2\6\1\0\1\6\1\0\6\6"+
    "\42\0\1\230\37\0\1\6\1\0\2\6\10\0\7\6"+
    "\1\231\7\6\1\0\1\6\1\0\6\6\17\0\1\6"+
    "\1\0\2\6\10\0\6\6\1\232\10\6\1\0\1\6"+
    "\1\0\6\6\42\0\1\233\37\0\1\6\1\0\2\6"+
    "\10\0\7\6\1\234\7\6\1\0\1\6\1\0\6\6"+
    "\17\0\1\6\1\0\2\6\10\0\17\6\1\235\1\236"+
    "\1\0\6\6\47\0\1\237\32\0\1\6\1\0\2\6"+
    "\10\0\14\6\1\240\2\6\1\0\1\6\1\0\6\6"+
    "\17\0\1\6\1\0\2\6\10\0\7\6\1\241\7\6"+
    "\1\0\1\6\1\0\6\6\36\0\1\242\43\0\1\6"+
    "\1\0\2\6\10\0\3\6\1\243\13\6\1\0\1\6"+
    "\1\0\6\6\35\0\1\244\44\0\1\6\1\0\2\6"+
    "\10\0\2\6\1\245\14\6\1\0\1\6\1\0\6\6"+
    "\17\0\1\6\1\0\2\6\10\0\5\6\1\246\11\6"+
    "\1\0\1\6\1\0\6\6\17\0\1\6\1\0\2\6"+
    "\10\0\17\6\1\0\1\6\1\247\1\250\5\6\17\0"+
    "\1\6\1\0\2\6\10\0\4\6\1\251\12\6\1\0"+
    "\1\6\1\0\6\6\17\0\1\6\1\0\2\6\10\0"+
    "\17\6\1\0\1\6\1\252\1\253\5\6\37\0\1\254"+
    "\42\0\1\6\1\0\2\6\10\0\4\6\1\255\12\6"+
    "\1\0\1\6\1\0\6\6\56\0\1\256\23\0\1\6"+
    "\1\0\2\6\10\0\17\6\1\0\1\6\1\0\1\6"+
    "\1\257\4\6\41\0\1\260\40\0\1\6\1\0\2\6"+
    "\10\0\6\6\1\261\10\6\1\0\1\6\1\0\6\6"+
    "\34\0\1\262\45\0\1\6\1\0\2\6\10\0\1\6"+
    "\1\263\15\6\1\0\1\6\1\0\6\6\57\0\1\264"+
    "\2\0\1\265\17\0\1\6\1\0\2\6\10\0\17\6"+
    "\1\0\1\6\1\0\2\6\1\266\2\6\1\267\41\0"+
    "\1\270\40\0\1\6\1\0\2\6\10\0\6\6\1\271"+
    "\10\6\1\0\1\6\1\0\6\6\17\0\1\6\1\0"+
    "\2\6\10\0\1\6\1\272\15\6\1\0\1\6\1\0"+
    "\6\6\42\0\1\273\37\0\1\6\1\0\2\6\10\0"+
    "\7\6\1\274\7\6\1\0\1\6\1\0\6\6\37\0"+
    "\1\275\42\0\1\6\1\0\2\6\10\0\4\6\1\276"+
    "\12\6\1\0\1\6\1\0\6\6\37\0\1\277\42\0"+
    "\1\6\1\0\2\6\10\0\4\6\1\300\12\6\1\0"+
    "\1\6\1\0\6\6\41\0\1\301\40\0\1\6\1\0"+
    "\2\6\10\0\6\6\1\302\10\6\1\0\1\6\1\0"+
    "\6\6\40\0\1\303\41\0\1\6\1\0\2\6\10\0"+
    "\5\6\1\304\11\6\1\0\1\6\1\0\6\6\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6783];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\2\1\1\11\20\1\15\11"+
    "\2\0\1\11\3\0\1\1\1\0\10\1\1\0\5\1"+
    "\1\0\5\1\1\0\1\1\1\0\1\1\1\0\2\1"+
    "\1\11\1\0\1\1\1\0\1\1\1\11\7\1\1\11"+
    "\5\1\1\11\7\1\1\0\1\1\1\11\1\1\1\0"+
    "\1\1\1\11\1\1\1\0\3\1\1\0\5\1\1\0"+
    "\3\1\1\0\3\1\1\0\1\1\1\0\2\1\1\11"+
    "\5\1\1\0\3\1\1\0\2\1\1\0\1\1\1\0"+
    "\5\1\1\0\2\1\1\0\1\1\1\11\1\1\1\0"+
    "\2\1\1\0\4\1\1\0\2\1\1\0\1\1\1\11"+
    "\1\1\1\0\1\1\1\11\1\1\1\0\1\1\2\11"+
    "\2\1\1\11\2\1\1\0\1\1\1\11\1\1\1\0"+
    "\1\1\1\11\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[196];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public static ArrayList<Errores> listaErrores = new ArrayList();
    public static ArrayList<Tokens> listaTokens = new ArrayList();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
  	yyline = 1; 
	yychar = 1; 
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 238) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { //System.out.println("Este es un error lexico: "+yytext()+ ", en la linea: "+yyline+", en la columna: "+yychar);
    //listaErrores.add(new Errores("Lexico", "Caracter no encontrado: "+ yytext(), yyline+"", yychar+""));
            } 
            // fall through
          case 55: break;
          case 2: 
            { 
            } 
            // fall through
          case 56: break;
          case 3: 
            { listaTokens.add(new Tokens(yytext(), "ENTERO", yyline+"", yychar+""));        return new Symbol(sym.ENTERO,yyline,yychar, yytext());
            } 
            // fall through
          case 57: break;
          case 4: 
            { listaTokens.add(new Tokens(yytext(), "PUNTO", yyline+"", yychar+""));         return new Symbol(sym.PUNTO, yyline, yychar, yytext());
            } 
            // fall through
          case 58: break;
          case 5: 
            { listaTokens.add(new Tokens(yytext(), "ID", yyline+"", yychar+""));            return new Symbol(sym.ID,yyline,yychar, yytext());
            } 
            // fall through
          case 59: break;
          case 6: 
            { yychar=1;
            } 
            // fall through
          case 60: break;
          case 7: 
            { listaTokens.add(new Tokens(yytext(), "PAR_IZQ", yyline+"", yychar+""));       return new Symbol(sym.PAR_IZQ, yyline, yychar, yytext());
            } 
            // fall through
          case 61: break;
          case 8: 
            { listaTokens.add(new Tokens(yytext(), "PAR_DER", yyline+"", yychar+""));       return new Symbol(sym.PAR_DER, yyline, yychar, yytext());
            } 
            // fall through
          case 62: break;
          case 9: 
            { listaTokens.add(new Tokens(yytext(), "LLAV_IZQ", yyline+"", yychar+""));      return new Symbol(sym.LLAV_IZQ, yyline, yychar, yytext());
            } 
            // fall through
          case 63: break;
          case 10: 
            { listaTokens.add(new Tokens(yytext(), "LLAV_DER", yyline+"", yychar+""));      return new Symbol(sym.LLAV_DER, yyline, yychar, yytext());
            } 
            // fall through
          case 64: break;
          case 11: 
            { listaTokens.add(new Tokens(yytext(), "COR_IZQ", yyline+"", yychar+""));       return new Symbol(sym.COR_IZQ, yyline, yychar, yytext());
            } 
            // fall through
          case 65: break;
          case 12: 
            { listaTokens.add(new Tokens(yytext(), "COR_DER", yyline+"", yychar+""));       return new Symbol(sym.COR_DER, yyline, yychar, yytext());
            } 
            // fall through
          case 66: break;
          case 13: 
            { listaTokens.add(new Tokens(yytext(), "ARROBA", yyline+"", yychar+""));        return new Symbol(sym.ARROBA, yyline, yychar, yytext());
            } 
            // fall through
          case 67: break;
          case 14: 
            { listaTokens.add(new Tokens(yytext(), "IGUAL", yyline+"", yychar+""));         return new Symbol(sym.IGUAL, yyline, yychar, yytext());
            } 
            // fall through
          case 68: break;
          case 15: 
            { listaTokens.add(new Tokens(yytext(), "MAYOR_QUE", yyline+"", yychar+""));     return new Symbol(sym.MAYOR_QUE, yyline, yychar, yytext());
            } 
            // fall through
          case 69: break;
          case 16: 
            { listaTokens.add(new Tokens(yytext(), "MENOR_QUE", yyline+"", yychar+""));     return new Symbol(sym.MENOR_QUE, yyline, yychar, yytext());
            } 
            // fall through
          case 70: break;
          case 17: 
            { listaTokens.add(new Tokens(yytext(), "PTCOMA", yyline+"", yychar+""));        return new Symbol(sym.PTCOMA, yyline, yychar, yytext());
            } 
            // fall through
          case 71: break;
          case 18: 
            { listaTokens.add(new Tokens(yytext(), "COMA", yyline+"", yychar+""));          return new Symbol(sym.COMA, yyline, yychar, yytext());
            } 
            // fall through
          case 72: break;
          case 19: 
            { listaTokens.add(new Tokens(yytext(), "DOSPUNTOS", yyline+"", yychar+""));     return new Symbol(sym.DOSPUNTOS, yyline, yychar, yytext());
            } 
            // fall through
          case 73: break;
          case 20: 
            { listaTokens.add(new Tokens(yytext(), "STRING", yyline+"", yychar+""));        return new Symbol(sym.STRING,yyline,yychar, yytext());
            } 
            // fall through
          case 74: break;
          case 21: 
            { listaTokens.add(new Tokens(yytext(), "CHAR", yyline+"", yychar+""));         return new Symbol(sym.CHAR,yyline,yychar, yytext());
            } 
            // fall through
          case 75: break;
          case 22: 
            { listaTokens.add(new Tokens(yytext(), "DECIMAL", yyline+"", yychar+""));       return new Symbol(sym.DECIMAL,yyline,yychar, yytext());
            } 
            // fall through
          case 76: break;
          case 23: 
            { listaTokens.add(new Tokens(yytext(), "PR_RES", yyline+"", yychar+""));         return new Symbol(sym.PR_RES, yyline, yychar, yytext());
            } 
            // fall through
          case 77: break;
          case 24: 
            { listaTokens.add(new Tokens(yytext(), "PR_ARR", yyline+"", yychar+""));         return new Symbol(sym.PR_ARR, yyline, yychar, yytext());
            } 
            // fall through
          case 78: break;
          case 25: 
            { listaTokens.add(new Tokens(yytext(), "PR_MOD", yyline+"", yychar+""));         return new Symbol(sym.PR_MOD, yyline, yychar, yytext());
            } 
            // fall through
          case 79: break;
          case 26: 
            { listaTokens.add(new Tokens(yytext(), "PR_MAX", yyline+"", yychar+""));         return new Symbol(sym.PR_MAX, yyline, yychar, yytext());
            } 
            // fall through
          case 80: break;
          case 27: 
            { listaTokens.add(new Tokens(yytext(), "PR_MUL", yyline+"", yychar+""));         return new Symbol(sym.PR_MUL, yyline, yychar, yytext());
            } 
            // fall through
          case 81: break;
          case 28: 
            { listaTokens.add(new Tokens(yytext(), "PR_MIN", yyline+"", yychar+""));         return new Symbol(sym.PR_MIN, yyline, yychar, yytext());
            } 
            // fall through
          case 82: break;
          case 29: 
            { listaTokens.add(new Tokens(yytext(), "PR_END", yyline+"", yychar+""));         return new Symbol(sym.PR_END, yyline, yychar, yytext());
            } 
            // fall through
          case 83: break;
          case 30: 
            { listaTokens.add(new Tokens(yytext(), "PR_DIV", yyline+"", yychar+""));         return new Symbol(sym.PR_DIV, yyline, yychar, yytext());
            } 
            // fall through
          case 84: break;
          case 31: 
            { listaTokens.add(new Tokens(yytext(), "PR_VAR", yyline+"", yychar+""));         return new Symbol(sym.PR_VOID, yyline, yychar, yytext());
            } 
            // fall through
          case 85: break;
          case 32: 
            { listaTokens.add(new Tokens(yytext(), "PR_SUM", yyline+"", yychar+""));         return new Symbol(sym.PR_SUM, yyline, yychar, yytext());
            } 
            // fall through
          case 86: break;
          case 33: 
            { listaTokens.add(new Tokens(yytext(), "PR_MODA", yyline+"", yychar+""));        return new Symbol(sym.PR_MODA, yyline, yychar, yytext());
            } 
            // fall through
          case 87: break;
          case 34: 
            { listaTokens.add(new Tokens(yytext(), "PR_EXEC", yyline+"", yychar+""));        return new Symbol(sym.PR_EXEC, yyline, yychar, yytext());
            } 
            // fall through
          case 88: break;
          case 35: 
            { listaTokens.add(new Tokens(yytext(), "PR_EJEX", yyline+"", yychar+""));        return new Symbol(sym.PR_EJEX, yyline, yychar, yytext());
            } 
            // fall through
          case 89: break;
          case 36: 
            { listaTokens.add(new Tokens(yytext(), "PR_EJEY", yyline+"", yychar+""));        return new Symbol(sym.PR_EJEY, yyline, yychar, yytext());
            } 
            // fall through
          case 90: break;
          case 37: 
            { listaTokens.add(new Tokens(yytext(), "PR_CHAR", yyline+"", yychar+""));        return new Symbol(sym.PR_CHAR, yyline, yychar, yytext());
            } 
            // fall through
          case 91: break;
          case 38: 
            { listaTokens.add(new Tokens(yytext(), "PR_PRINT", yyline+"", yychar+""));       return new Symbol(sym.PR_PRINT, yyline, yychar, yytext());
            } 
            // fall through
          case 92: break;
          case 39: 
            { listaTokens.add(new Tokens(yytext(), "PR_MEDIA", yyline+"", yychar+""));       return new Symbol(sym.PR_MEDIA, yyline, yychar, yytext());
            } 
            // fall through
          case 93: break;
          case 40: 
            { listaTokens.add(new Tokens(yytext(), "PR_LABEL", yyline+"", yychar+""));       return new Symbol(sym.PR_LABEL, yyline, yychar, yytext());
            } 
            // fall through
          case 94: break;
          case 41: 
            { listaTokens.add(new Tokens(yytext(), "PR_DOUBLE", yyline+"", yychar+""));      return new Symbol(sym.PR_DOUBLE, yyline, yychar, yytext());
            } 
            // fall through
          case 95: break;
          case 42: 
            { listaTokens.add(new Tokens(yytext(), "PR_VALUES", yyline+"", yychar+""));      return new Symbol(sym.PR_VALUES, yyline, yychar, yytext());
            } 
            // fall through
          case 96: break;
          case 43: 
            { listaTokens.add(new Tokens(yytext(), "PR_COLUMN", yyline+"", yychar+""));      return new Symbol(sym.PR_COLUMN, yyline, yychar, yytext());
            } 
            // fall through
          case 97: break;
          case 44: 
            { listaTokens.add(new Tokens(yytext(), "PR_TITULO", yyline+"", yychar+""));      return new Symbol(sym.PR_TITULO, yyline, yychar, yytext());
            } 
            // fall through
          case 98: break;
          case 45: 
            { listaTokens.add(new Tokens(yytext(), "PR_PROGRAM", yyline+"", yychar+""));     return new Symbol(sym.PR_PROGRAM, yyline, yychar, yytext());
            } 
            // fall through
          case 99: break;
          case 46: 
            { listaTokens.add(new Tokens(yytext(), "PR_MEDIANA", yyline+"", yychar+""));     return new Symbol(sym.PR_MEDIANA, yyline, yychar, yytext());
            } 
            // fall through
          case 100: break;
          case 47: 
            { listaTokens.add(new Tokens(yytext(), "PR_CONSOLE", yyline+"", yychar+""));     return new Symbol(sym.PR_CONSOLE, yyline, yychar, yytext());
            } 
            // fall through
          case 101: break;
          case 48: 
            { listaTokens.add(new Tokens(yytext(), "PR_TITULOX", yyline+"", yychar+""));     return new Symbol(sym.PR_TITULOX, yyline, yychar, yytext());
            } 
            // fall through
          case 102: break;
          case 49: 
            { listaTokens.add(new Tokens(yytext(), "PR_TITULOY", yyline+"", yychar+""));     return new Symbol(sym.PR_TITULOY, yyline, yychar, yytext());
            } 
            // fall through
          case 103: break;
          case 50: 
            { listaTokens.add(new Tokens(yytext(), "PR_GRAPHPIE", yyline+"", yychar+""));    return new Symbol(sym.PR_GRAPHPIE, yyline, yychar, yytext());
            } 
            // fall through
          case 104: break;
          case 51: 
            { listaTokens.add(new Tokens(yytext(), "PR_GRAPHBAR", yyline+"", yychar+""));    return new Symbol(sym.PR_GRAPHBAR, yyline, yychar, yytext());
            } 
            // fall through
          case 105: break;
          case 52: 
            { listaTokens.add(new Tokens(yytext(), "PR_VARIANZA", yyline+"", yychar+""));    return new Symbol(sym.PR_VARIANZA, yyline, yychar, yytext());
            } 
            // fall through
          case 106: break;
          case 53: 
            { listaTokens.add(new Tokens(yytext(), "PR_GRAPHLINE", yyline+"", yychar+""));   return new Symbol(sym.PR_GRAPHLINE, yyline, yychar, yytext());
            } 
            // fall through
          case 107: break;
          case 54: 
            { listaTokens.add(new Tokens(yytext(), "PR_HISTOGRAM", yyline+"", yychar+""));   return new Symbol(sym.PR_HISTOGRAM, yyline, yychar, yytext());
            } 
            // fall through
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
