
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 65)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_DER = 9;
  public static final int DOSPUNTOS = 20;
  public static final int CHAR = 6;
  public static final int PR_COLUMN = 41;
  public static final int PR_TITULO = 47;
  public static final int PR_MODA = 35;
  public static final int ENTERO = 3;
  public static final int PR_VOID = 24;
  public static final int COR_DER = 13;
  public static final int PR_TITULOY = 51;
  public static final int PR_DIV = 31;
  public static final int PR_TITULOX = 50;
  public static final int PR_VARIANZA = 36;
  public static final int PR_VALUES = 52;
  public static final int PR_MIN = 38;
  public static final int IGUAL = 15;
  public static final int ARROBA = 14;
  public static final int PR_MEDIA = 33;
  public static final int PR_MUL = 30;
  public static final int PR_LABEL = 53;
  public static final int PR_EXEC = 42;
  public static final int PR_MOD = 32;
  public static final int LLAV_IZQ = 10;
  public static final int ID = 2;
  public static final int PR_MEDIANA = 34;
  public static final int PR_PRINT = 40;
  public static final int EOF = 0;
  public static final int PR_PROGRAM = 22;
  public static final int DECIMAL = 4;
  public static final int error = 1;
  public static final int PRUEBA = 5;
  public static final int COMA = 19;
  public static final int PR_HISTOGRAM = 46;
  public static final int MAYOR_QUE = 16;
  public static final int PR_GRAPHPIE = 43;
  public static final int PAR_IZQ = 8;
  public static final int PR_GRAPHLINE = 45;
  public static final int PR_CHAR = 26;
  public static final int PR_END = 23;
  public static final int PR_SUM = 28;
  public static final int PR_GRAPHBAR = 44;
  public static final int PR_ARR = 27;
  public static final int PUNTO = 21;
  public static final int PR_MAX = 37;
  public static final int COR_IZQ = 12;
  public static final int PR_EJEY = 49;
  public static final int PR_EJEX = 48;
  public static final int PTCOMA = 18;
  public static final int STRING = 7;
  public static final int LLAV_DER = 11;
  public static final int MENOR_QUE = 17;
  public static final int PR_DOUBLE = 25;
  public static final int PR_CONSOLE = 39;
  public static final int PR_RES = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "ENTERO",
  "DECIMAL",
  "PRUEBA",
  "CHAR",
  "STRING",
  "PAR_IZQ",
  "PAR_DER",
  "LLAV_IZQ",
  "LLAV_DER",
  "COR_IZQ",
  "COR_DER",
  "ARROBA",
  "IGUAL",
  "MAYOR_QUE",
  "MENOR_QUE",
  "PTCOMA",
  "COMA",
  "DOSPUNTOS",
  "PUNTO",
  "PR_PROGRAM",
  "PR_END",
  "PR_VOID",
  "PR_DOUBLE",
  "PR_CHAR",
  "PR_ARR",
  "PR_SUM",
  "PR_RES",
  "PR_MUL",
  "PR_DIV",
  "PR_MOD",
  "PR_MEDIA",
  "PR_MEDIANA",
  "PR_MODA",
  "PR_VARIANZA",
  "PR_MAX",
  "PR_MIN",
  "PR_CONSOLE",
  "PR_PRINT",
  "PR_COLUMN",
  "PR_EXEC",
  "PR_GRAPHPIE",
  "PR_GRAPHBAR",
  "PR_GRAPHLINE",
  "PR_HISTOGRAM",
  "PR_TITULO",
  "PR_EJEX",
  "PR_EJEY",
  "PR_TITULOX",
  "PR_TITULOY",
  "PR_VALUES",
  "PR_LABEL"
  };
}

